TASK/ASPCORE_TASK_Palestra/ASPCORE_TASK_Palestra/Controllers/UtenteController.cs
using ASPCORE_TASK_Palestra.Data;
using ASPCORE_TASK_Palestra.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using MongoDB.Bson;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ASPCORE_TASK_Palestra.Controllers
{
    public class UtenteController : Controller
    {
        private UtenteRepo _repoUtente;
        private CorsoRepo _repoCorso;
        private IscrizioneRepo _repoIscrizione;

        public UtenteController(IConfiguration config)
        {
            if(_repoUtente == null)
            {
                bool isOnline = config.GetValue<bool>("IsOnline");

                string connString = isOnline ?
                    config.GetValue<string>("MongoDbSettings:OnlineDb") :
                    config.GetValue<string>("MongoDbSettings:LocalDb");

                string dbString = config.GetValue<string>("MongoDbSettings:NomeDb");

                _repoUtente = new UtenteRepo(connString, dbString);
                _repoCorso = new CorsoRepo(connString, dbString);
                _repoIscrizione = new IscrizioneRepo(connString, dbString);
            }
        }
        public RedirectResult Logout()
        {
            HttpContext.Session.Clear();
            return Redirect("/Utente/Login");
        }
        public IActionResult Login()
        {
            if (HttpContext.Session.GetString("isLogged") == null)
                return View();
            return Redirect("/Utente/IMieiCorsi");
        }

        public RedirectResult LoginCheck(Utente objUtente)
        {
            Utente loginAttempt = _repoUtente.GetByEmail(objUtente.Email);
            if(loginAttempt != null && loginAttempt.Password == objUtente.Password)
            {
                HttpContext.Session.SetString("isLogged", loginAttempt.Email);
                return Redirect("/Utente/MyCourses");
            }
            else
            {
                return Redirect("/Utente/Login");
            }
        }

        public IActionResult SignUp()
        {
            return View();
        }

        public IActionResult SignedIn()
        {
            return View();
        }

        [HttpPost]
        public IActionResult SignUp(Utente objUtente)
        {
            if (ModelState.IsValid)
            {
                _repoUtente.Insert(objUtente);
                return Redirect("/Utente/SignedIn");
            }
            return View(objUtente);
            
        }
        public IActionResult Courses()
        {
            return View(_repoCorso.GetAll().ToList());
        }

        public IActionResult IscrizioneCorso(string codice)
        {
            ObjectId idCorso = _repoCorso.GetByCodice(codice).Id;
            string currentUser = HttpContext.Session.GetString("isLogged");
            if (currentUser != null)
            {
                //Prendo i dati dell'utente al momento loggato
                Utente temp = _repoUtente.GetByEmail(currentUser);

                //Se l'utente non è iscitto ad alcun corso allora lo iscrivo direttamente
                if(_repoIscrizione.GetAll().Where(i => i.UtenteId == temp.Id) == null)
                {
                    //Inizializzo una nuova iscrizione al corso selezionato
                    Iscrizione newSub = new Iscrizione()
                    {
                        CorsoId = idCorso,
                        UtenteId = temp.Id,
                        IscrizioneId = new ObjectId(),
                        DataIscrizione = DateTime.Now,
                        CorsoRIF = _repoCorso.GetById(idCorso),
                        UtenteRIF = temp
                    };
                    temp.ElencoIscrizioni.Add(newSub);
                    _repoIscrizione.Insert(newSub);
                    return Redirect("/Utente/MyCourses");
                }
                else
                {
                    var findCorso = _repoIscrizione.GetAll()
                        .Where(i => i.CorsoId == idCorso)
                        .Where(i => i.UtenteId == temp.Id)
                        .FirstOrDefault();
                    //L'utente non è già iscritto al corso, ce lo iscrivo
                    if (findCorso == null)
                    {
                        //Inizializzo una nuova iscrizione al corso selezionato
                        Iscrizione newSub = new Iscrizione()
                        {
                            CorsoId = idCorso,
                            UtenteId = temp.Id,
                            IscrizioneId = new ObjectId(),
                            DataIscrizione = DateTime.Now,
                            CorsoRIF = _repoCorso.GetById(idCorso),
                            UtenteRIF = temp
                        };
                        temp.ElencoIscrizioni.Add(newSub);
                        _repoIscrizione.Insert(newSub);
                        return Redirect("/Utente/MyCourses");
                    }
                    //L'utente è già iscritto al corso
                    else
                        return Redirect("/Utente/MyCourses");
                }
            }
            return Redirect("/Utente/Login");
        }

        public IActionResult MyCourses()
        {
            string currentUser = HttpContext.Session.GetString("isLogged");
            if (currentUser != null)
            {
                Utente temp = _repoUtente.GetByEmail(currentUser);
                List<Corso> elencoCorsi = _repoIscrizione.GetAll()
                    .Where(i => i.UtenteId == temp.Id)
                    .Select(i => _repoCorso.GetById(i.CorsoId)).ToList();


                return View(elencoCorsi);
            }
            return Redirect("/Utente/Login");
        }

        public RedirectResult Disiscriviti(string codice)
        {
            ObjectId idCorso = _repoCorso.GetByCodice(codice).Id;
            string currentUser = HttpContext.Session.GetString("isLogged");
            if (currentUser != null)
            {
                Utente temp = _repoUtente.GetByEmail(currentUser);
                Iscrizione queryIscrizione = _repoIscrizione.GetAll()
                    .Where(i => i.CorsoId == idCorso)
                    .Where(i => i.UtenteId == temp.Id)
                    .FirstOrDefault();
                if (_repoIscrizione.Delete(queryIscrizione.IscrizioneId))
                {
                    temp.ElencoIscrizioni.Remove(queryIscrizione);
                    return Redirect("/Utente/MyCourses");
                }
            }
            return Redirect("/Utente/Courses");
        }

        public IActionResult AreaPersonale()
        {
            string currentUser = HttpContext.Session.GetString("isLogged");
            if(currentUser != null)
            {
                ViewBag.TempClass = "disabled";
                Utente temp = _repoUtente.GetByEmail(currentUser);
                return View(temp);
            }
            return Redirect("/Utente/Login");
        }

        public IActionResult ModificaDati()
        {
            string currentUser = HttpContext.Session.GetString("isLogged");
            if (currentUser != null)
            {
                ViewBag.TempClass = "disabled";
                Utente temp = _repoUtente.GetByEmail(currentUser);
                return View(temp);
            }
            return Redirect("/Utente/Login");
        }

        [HttpPost]
        public IActionResult ModificaDati(Utente objUtente)
        {
            if(ModelState.IsValid)
            {
                if(_repoUtente.Update(objUtente))
                    return Redirect("/Utente/AreaPersonale");
            }
            return View(objUtente);
        }
    }
}

TASK/ASPCORE_TASK_Palestra/ASPCORE_TASK_Palestra/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor
@{ 
    string username = HttpContextAccessor.HttpContext.Session.GetString("isLogged");
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="~/css/style.css" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-custom">
        <a class="navbar-brand" href="/Utente/Login">Home</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end" id="navbarNavDropdown">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="/Utente/Courses">Lista Corsi</a>
                </li>
                @if (username != null)
                {
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            @username
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" href="/Utente/AreaPersonale">Il Mio Profilo</a>
                            <a class="dropdown-item" href="/Utente/MyCourses">I Miei Corsi</a>
                            <a class="dropdown-item" asp-controller="Utente" asp-action="Logout">Logout</a>
                        </div>
                        
                    </li>
                }
            </ul>
        </div>
    </nav>

    <div class="container mt-5">
        @RenderBody()
    </div>

    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="~/js/script.js"></script>
</body>
</html>